spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:

  sms:
    access-key-id: LTAI5tGYZpmF9v2PkTDeiazq
    access-key-secret: PuZYqg9wyVlH5TK9gGJI42PgatAn6h
    endpoint: dysmsapi.aliyuncs.com
    signName: 阿里云短信测试
    templateCode: SMS_154950909

  # 发送邮件配置
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口
    username: 1539816041@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: ubgsaazecgzaheih # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
        debug: true
    from: 1539816041@qq.com # 发送方邮件，配在yml中可方便更改

